language: r
cache: packages

os:
  - linux

r_packages:
  - devtools
  - hunspell

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  # TMHMM 
  - |
    Rscript -e \
    "source(\"R/install_tmhmm.R\"); \
      source(\"R/get_default_tmhmm_folder.R\"); \
      source(\"R/get_tmhmm_url.R\"); \
      source(\"R/is_tmhmm_installed.R\"); \
      source(\"R/is_tmhmm_set_up.R\"); \
      source(\"R/set_up_tmhmm.R\"); \
      install_tmhmm(get_tmhmm_url())"
  - echo "AAAAAAAAAAAAAAAAAAAAAAAA" | ~/.local/share/tmhmm-2.0c/bin/tmhmm 
  - export PATH=~/.local/share/tmhmm-2.0c/bin:$PATH
  - echo "AAAAAAAAAAAAAAAAAAAAAAAA" | ~/.local/share/tmhmm-2.0c/bin/tmhmm 
  # proselint
  - sudo pip install proselint

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi

after_failure:
  - ls