# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      matrix:
        include:
          - install_tmhmm: "true" 
          - install_tmhmm: "false"

    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Show TMHMM
        env:
          INSTALL_TMHMM: ${{ matrix.install_tmhmm }}
        run: echo "$INSTALL_TMHMM"

      - name: If statement on TMHMM is true
        env:
          INSTALL_TMHMM: ${{ matrix.install_tmhmm }}
        run: if [[ "$INSTALL_TMHMM" == true ]]; then echo "Yay!"; fi

      - name: Show location
        run: pwd

      - name: If statement on TMHMM is false
        env:
          INSTALL_TMHMM: ${{ matrix.install_tmhmm }}
        run: if [[ "$INSTALL_TMHMM" == false ]]; then echo "Nay!"; fi

      - name: Show TMHMM install script
        env:
          INSTALL_TMHMM: ${{ matrix.install_tmhmm }}
        run: if [[ "$INSTALL_TMHMM" == true ]]; then cat scripts/install_tmhmm.sh; fi

      - name: Install TMHMM
        env:
          INSTALL_TMHMM: ${{ matrix.install_tmhmm }}
        run: if [[ "$INSTALL_TMHMM" == true ]]; then ./scripts/install_tmhmm.sh; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: if [[ "$INSTALL_TMHMM" == true ]]; then Rscript -e 'covr::codecov()'; fi

      - name: Lint
        run: if [[ "$INSTALL_TMHMM" == false ]]; then Rscript -e 'lintr::lint_package()'; fi

